[SC-989][SC-990] Solidity 0.8.23, OZ 5.0.0
1inch/token-plugins pull request #31
Opened 2023-11-14 16:49 UTC by zZoMROT

<img width="1144" alt="Снимок экрана 2023-12-07 в 11 23 14" src="https://github.com/1inch/token-plugins/assets/3616087/7182f5af-6c3b-4945-a71f-90b33b55707a">

2023-12-05 12:55 UTC, k06a commented
Please add gas reports comparison

2023-12-07 09:13 UTC, ZumZoom requested changes

2023-12-07 09:13 UTC, ZumZoom commented on .solcover.js
Reuse `.solcover.js` from here https://github.com/1inch/solidity-utils/blob/master/.solcover.js

2023-12-07 09:24 UTC, zZoMROT commented
> Please add gas reports comparison

Done. You can find it in first comment of this PR

2023-12-19 09:26 UTC, ZumZoom approved these changes

2023-12-19 09:26 UTC, merged